name: pytest
on: [push, pull_request, workflow_dispatch]
jobs:
  run:
    name: Run unit tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: 
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.8, 3.9, "3.10", "3.11"]
    steps:
    - uses: actions/checkout@master
    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@master
      with:
        python-version: ${{ matrix.python-version }}
    - name: Static code checking with pyflakes
      run: |
        pip install pyflakes
        pyflakes mkdocs_charts_plugin
    - name: Generate coverage report
      run: |
        pip install -r tests/test_requirements.txt
        pip install .
        pytest --cov=mkdocs_charts_plugin
